{
 "title": "PartsUnlimited Perf",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Environment", "query": "Development,Production" },
   { "name": "Canary", "query": "pu_product_add" }
  ]
 },
 "panels": [
  {
   "title": "Request Count increase per canary",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(pu_product_add{environment=\"$Environment\",canary=~\"${Canary:pipe}\"}[2m])) by (canary)",
     "legendFormat": "{{canary}}"
    }
   ]
  },
  {
   "title": "Response Time AppDex 100ms",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(\r\n  sum(rate(http_request_duration_seconds_bucket{le=\"0.1\",canary=~\"${Canary:pipe}\"}[5m]))\r\n+\r\n  sum(rate(http_request_duration_seconds_bucket{le=\"0.5\",canary=~\"${Canary:pipe}\"}[5m]))\r\n) / 2 / sum(rate(http_request_duration_seconds_count{canary=~\"${Canary:pipe}\"}[5m])) * 100"
    }
   ]
  },
  {
   "title": "SQL Dependency Perf",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "pu_dependency_duration_bucket{environment=\"$Environment\",canary=~\"${Canary:pipe}\"}"
    }
   ]
  },
  {
   "title": "Response Performance",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{canary=~\"${Canary:pipe}\"}[5m])) by (le)) * 1e3",
     "legendFormat": "95th Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_request_duration_seconds_bucket{canary=~\"${Canary:pipe}\"}[5m])) by (le)) * 1e3",
     "legendFormat": "Median"
    },
    {
     "expr": "sum(rate(http_request_duration_seconds_sum{canary=~\"${Canary:pipe}\"}[5m])) / sum(rate(http_request_duration_seconds_count{canary=~\"${Canary:pipe}\"}[5m])) * 1e3",
     "legendFormat": "Mean"
    }
   ]
  },
  {
   "title": "Average Http Response Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum{environment=\"$Environment\",canary=~\"${Canary:pipe}\"}[5m])) by (canary)",
     "legendFormat": "{{canary}}"
    }
   ]
  }
 ]
}